##################### Training Control #####################
deterministic: False
use_compile: True
inference_mode: False # If this one is True, use inference
seed: 1234
max_epochs: 100

##################### Distributed Training Control #####################
devices: 1
num_nodes: 1
strategy: auto

##################### Dataset Setting #####################
dataset_class_name: n_imagenet
dataset_dir: dataset
repr_names: ['event_voxel']
split_ratios: [0.8, 0.1, 0.1]
batch_size: 128
test_batch_size: 32
num_workers: 8
persistent_workers: True

##################### Model Architecture #####################
model_class_name: unimodal
in_size: [640, 480]
in_channels: 10
latent_size: [20, 15]
latent_channels: 64
stage_depths: [3, 3, 9, 3]
base_channels: 32
channel_multipliers: [1, 2, 4, 8]
drop_path_rate: 0.1
use_grn: True
save_skips: True
pooling_method: 'none'

##################### Optimizers and Loss Functions #####################
weight_decay: 1e-6 # Default L2 Regularization
lr: 1e-3
lr_scheduler: step
lr_decay_epochs: 10
lr_decay_rate: 0.5
lr_decay_min_lr: 1e-6


###################### Tensorboard Logger Setting #####################
log_dir_root: 'lightning_logs'
experiment_name: 'hots_unimodal'

##################### Checkpoint & Restart Control #####################
enable_checkpointing: True