##################### Training Control #####################
deterministic: False
use_compile: True
inference_mode: False # If this one is True, use inference
seed: 1234
max_epochs: 100

##################### Distributed Training Control #####################
devices: 1
num_nodes: 1
strategy: auto

##################### Dataset Setting #####################
dataset_class_name: n_imagenet
dataset_dir: dataset
repr_names: ['event_voxel', 'time_surface']
split_ratios: [0.8, 0.1, 0.1]
batch_size: 128
test_batch_size: 32
num_workers: 8
persistent_workers: True

##################### Model Architecture #####################
model_class_name: unimodal
in_channels_1: 10
in_channels_2: 10
latent_channels: 64
in_size_1: [640, 480]
in_size_2: [640, 480]
latent_size: [20, 15]
stage_depths: [3, 3, 9, 3]
base_channels: 32
channel_multipliers: [1, 2, 4, 8]
drop_path_rate: 0.1
use_grn: True
save_skips: False
pooling_method: 'conv'
pooling_channels: [128, 256]
pooling_kernel_size: [2, 2]
pooling_strides: [2, 2]
gem_pooling_p: 3.0
gem_pooling_learnable_p: True
final_latent_embedding_dim: 2048

##################### Optimizers and Loss Functions #####################
weight_decay: 1e-6 # Default L2 Regularization
lr: 1e-3
lr_scheduler: step
lr_decay_epochs: 10
lr_decay_rate: 0.5
lr_decay_min_lr: 1e-6
global_CL_lambda: 0.5
global_multipos_info_nce_temperature: 0.7
global_multipos_info_nce_eps: 1e-8
dense_CL_lambda: 0.5
dense_info_nce_temperature: 0.07
dense_info_nce_include_spatial_negatives: True
dense_info_nce_neighborhood: 0
dense_info_nce_eps: 1e-8

###################### Tensorboard Logger Setting #####################
log_dir_root: 'lightning_logs'
experiment_name: '[event_voxel]x[time_surface]'

##################### Checkpoint & Restart Control #####################
enable_checkpointing: True